Matrices

In [4]:
import numpy as np

In [6]:
np.random.seed(1)
np.random.randint(1,21, size =15)

array([ 6, 12, 13,  9, 10, 12,  6, 16,  1, 17,  2, 13,  8, 14,  7])

In [12]:
L = [i for i in np.random.randint(1,21, size = 40) if i%2==0]
L.sort()
L

[4, 6, 8, 8, 10, 10, 10, 14, 16, 16, 16, 18, 18, 18, 18, 20, 20]

In [13]:
L.pop(1)

6

In [14]:
L_arreglo = np.array(L)
L_arreglo

array([ 4,  8,  8, 10, 10, 10, 14, 16, 16, 16, 18, 18, 18, 18, 20, 20])

In [15]:
len(L_arreglo)

16

In [29]:
L_Matriz = L_arreglo.reshape(4,4)
L_Matriz

array([[ 4,  8,  8, 10],
       [10, 10, 14, 16],
       [16, 16, 18, 18],
       [18, 18, 20, 20]])

In [30]:
M_matriz = np.array([2,3,14,19,13,0,25,6,9,2,8,9,1,4,5,17]).reshape(4,4)
M_matriz

array([[ 2,  3, 14, 19],
       [13,  0, 25,  6],
       [ 9,  2,  8,  9],
       [ 1,  4,  5, 17]])

In [32]:
N = M_matriz @ L_Matriz
N

array([[604, 612, 690, 700],
       [560, 612, 674, 700],
       [346, 382, 424, 446],
       [430, 434, 494, 504]])